### ISSUE TITLE
document steps for pushing package to PyPI

### ISSUE THREAD

**Issue by turbomam** [turbomam/linkml-template-audit#2]
A release-triggered action`pypi-publish.yaml` is already present

```    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@v1.2.2
      with:
        user: __token__
        password: ${ secrets.pypi_password }
```

I replaced that based on https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

```
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
```

and created `GitHub Actions CI/CD — turbomam/linkml-template-audit ` tokens in PyPi and PyPi test. I saved those as `PYPI_API_TOKEN` and `TEST_PYPI_API_TOKEN` `Repository secrets` in this GitHub repository's settings->secrets.
